# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_replication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15msg_replication.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x19MessageReplicationRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"?\n\x1aMessageReplicationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\")\n\x15ReplicatedMessageList\x12\x10\n\x08messages\x18\x01 \x03(\t2\x9c\x01\n\x0cSecondaryLog\x12L\n\x11replicate_message\x12\x1a.MessageReplicationRequest\x1a\x1b.MessageReplicationResponse\x12>\n\x0cget_messages\x12\x16.google.protobuf.Empty\x1a\x16.ReplicatedMessageListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_replication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEREPLICATIONREQUEST._serialized_start=54
  _MESSAGEREPLICATIONREQUEST._serialized_end=110
  _MESSAGEREPLICATIONRESPONSE._serialized_start=112
  _MESSAGEREPLICATIONRESPONSE._serialized_end=175
  _REPLICATEDMESSAGELIST._serialized_start=177
  _REPLICATEDMESSAGELIST._serialized_end=218
  _SECONDARYLOG._serialized_start=221
  _SECONDARYLOG._serialized_end=377
# @@protoc_insertion_point(module_scope)
